version: "3" 
services: # Not the same as Kubernetes service
  kavanet.io: # Service name
    container_name: site
    build: # Command
      context: . # This folder on the left
      dockerfile: Dockerfile
    image: gatsby-site-image
    hostname: first-service
    ports: 
      - "3000:80"