version: "3"
services: # Not the same as Kubernetes service
  kavanet.io: # Service name
    container_name: kavanet.io
    build: # Command
      context: . # This folder on the left
      dockerfile: ./Dockerfile
    image: kavanet.io
    hostname: kavanet.io
    ports:
      - 80:80
