name: kavanet-io

namespace: kavanet-io

deployment:
  - name: kavanet-io
    image: 192.168.1.61:5000/kavanet.io
    ports:
    - port: 80

service:
  clusterIP:
    - name: kavanet-io
      selector: kavanet-io
      ports:
      - port: 80

ingress:
  - name: kavanet-io
    selector: kavanet-io
    path: /
    port: 80
    host: kavanet.io